Repository woowa-techcamp-2021/deal-18, pull requests merged in 2021-07, with the labels that each got.

#2 [FE] 웹팩, 바벨 설정 완료
  babel.config.js
  package-lock.json
  package.json
  webpack.config.js
Labels: FE, setting

#6 프로젝트 기본 설정 (#4, #5)
  .prettierrc.json
  backend/app.js
  backend/routes/routes.js
  configs/config.dev.json
  frontend/babel.config.js
  frontend/public/index.html
  frontend/src/index.js
  frontend/webpack.config.js
  package.json
Labels: setting

#12 [BE] 백엔드 그라운트 코드 개발 (#11)
  .gitignore
  backend/app.js
  backend/routes/apiRouter.js
  backend/routes/routes.js
  package-lock.json
  package.json
Labels: BE, feat, setting

#14 [FE] 페이지 폴더 구조 변경 및 홈페이지 마크업
  frontend/public/assets/homepage/category.svg
  frontend/public/assets/homepage/location.svg
  frontend/public/assets/homepage/menu.svg
  frontend/public/assets/homepage/user.svg
  frontend/public/assets/product/bigHeart.svg
  frontend/public/assets/product/comment.svg
  frontend/public/assets/product/filledBigHeart.svg
  frontend/public/assets/product/heart.svg
  frontend/public/assets/product/product-menu.svg
  frontend/public/img/ImageLarge-0.png
  frontend/public/img/ImageLarge-1.png
  frontend/public/img/ImageLarge-2.png
  frontend/public/img/ImageLarge-3.png
  frontend/public/img/ImageLarge-4.png
  frontend/public/img/ImageLarge-5.png
  frontend/public/img/ImageLarge-6.png
  frontend/public/img/ImageLarge-7.png
  frontend/public/img/ImageLarge-8.png
  frontend/public/img/ImageLarge-9.png
  frontend/src/App.js
  frontend/src/components/ProductList/ProductItem.js
  frontend/src/components/ProductList/index.js
  frontend/src/components/ProductList/style.scss
  frontend/src/components/TopBar/index.js
  frontend/src/components/TopBar/style.scss
  frontend/src/components/TownPage/index.js
  frontend/src/index.js
  frontend/src/pages/CategoryPage/index.js
  frontend/src/pages/CategoryPage/style.scss
  frontend/src/pages/HomePage.js
  frontend/src/pages/HomePage/index.js
  frontend/src/pages/HomePage/style.scss
  frontend/src/store/page.js
  frontend/src/style/style.css
  frontend/src/style/style.scss
  frontend/src/style/variables.scss
  frontend/src/utils/convertToString.js
  frontend/src/utils/dom.js
Labels: FE, feat, refactor

#16 [FE] 동네 페이지 마크업 및 모달 구현
  frontend/public/assets/locationPage/locationAddBtn.svg
  frontend/public/assets/locationPage/locationDeleteBtn.svg
  frontend/public/assets/topbar/backBtn.svg
  frontend/src/components/Common/CommonTopBar/index.js
  frontend/src/components/Common/CommonTopBar/style.scss
  frontend/src/components/Common/Modal/index.js
  frontend/src/components/Dropdown/LocationDropdown.js
  frontend/src/components/Dropdown/style.scss
  frontend/src/components/LocationList/LocationItem.js
  frontend/src/components/LocationList/index.js
  frontend/src/components/LocationList/style.scss
  frontend/src/components/Popup/LocationInputPopup.js
  frontend/src/components/Popup/style.scss
  frontend/src/components/TopBar/index.js
  frontend/src/components/TopBar/style.scss
  frontend/src/pages/LocationEditPage/index.js
  frontend/src/pages/LocationEditPage/style.scss
  frontend/src/store/store.js
  frontend/src/style/style.scss
  frontend/src/style/variables.scss
Labels: FE, feat

#20 [Chore] 모달 개선, SCSS 변수명, Modal, TopBar 명칭 수정
  frontend/src/components/CategoryContainer/style.scss
  frontend/src/components/Common/CommonTopBar/style.scss
  frontend/src/components/Common/Modal/index.js
  frontend/src/components/Dropdown/style.scss
  frontend/src/components/LocationList/style.scss
  frontend/src/components/LoginForm/style.scss
  frontend/src/components/LogoutForm/style.scss
  frontend/src/components/MainTopBar/index.js
  frontend/src/components/MainTopBar/style.scss
  frontend/src/components/Popup/style.scss
  frontend/src/components/RegisterForm/style.scss
  frontend/src/pages/HomePage/index.js
  frontend/src/style/variables.scss
Labels: FE, refactor

#22 [FE] 라우터 구현 및 부분 적용
  frontend/src/App.js
  frontend/src/components/Common/CommonTopBar/index.js
  frontend/src/components/Dropdown/LocationDropdown.js
  frontend/src/components/LoginForm/index.js
  frontend/src/components/MainTopBar/index.js
  frontend/src/index.js
  frontend/src/lib/route.js
  frontend/src/pages/HomePage/index.js
  frontend/src/pages/LocationEditPage/index.js
Labels: FE, feat

#29 [FE] 채팅, 채팅하기 페이지 마크업
  frontend/public/assets/chatPage/ChatDeleteButton.svg
  frontend/public/assets/chatPage/ChatSendButton.svg
  frontend/src/components/ChatList/ChatItem.js
  frontend/src/components/ChatList/index.js
  frontend/src/components/ChatList/style.scss
  frontend/src/components/Chatting/ChatDeleteBtn.js
  frontend/src/components/Chatting/ChatProductInfo/index.js
  frontend/src/components/Chatting/ChatProductInfo/style.scss
  frontend/src/components/Chatting/Chatting.js
  frontend/src/components/Chatting/style.scss
  frontend/src/components/Common/CommonTopBar/index.js
  frontend/src/components/MainTopBar/index.js
  frontend/src/components/MenuTab/MenuTabItem.js
  frontend/src/components/MenuTab/index.js
  frontend/src/components/MenuTab/style.scss
  frontend/src/components/ProductList/index.js
  frontend/src/components/ProductList/style.scss
  frontend/src/index.js
  frontend/src/pages/ChatListPage/index.js
  frontend/src/pages/ChatPage/index.js
  frontend/src/pages/ChatPage/style.scss
  frontend/src/pages/HomePage/index.js
  frontend/src/pages/LocationEditPage/style.scss
  frontend/src/pages/MenuPage/index.js
  frontend/src/pages/MenuPage/style.scss
  frontend/src/store/menuPage.js
  frontend/src/style/style.scss
Labels: FE, feat

#30 [FE] 글쓰기 페이지 마크업 및 몇몇 로직
  frontend/public/assets/homepage/postButton.svg
  frontend/public/assets/postPage/imgDeleteButton.svg
  frontend/public/assets/postPage/locationIcon.svg
  frontend/public/assets/postPage/pictureIcon.svg
  frontend/src/components/Common/CommonTopBar/index.js
  frontend/src/components/Common/CommonTopBar/style.scss
  frontend/src/components/PostProductForm/FormImgList/index.js
  frontend/src/components/PostProductForm/FormImgList/style.scss
  frontend/src/components/PostProductForm/FormTitleNCategory/index.js
  frontend/src/components/PostProductForm/FormTitleNCategory/style.scss
  frontend/src/components/PostProductForm/index.js
  frontend/src/components/PostProductForm/style.scss
  frontend/src/index.js
  frontend/src/pages/HomePage/index.js
  frontend/src/pages/HomePage/style.scss
  frontend/src/pages/PostPage/index.js
  frontend/src/pages/PostPage/style.scss
  frontend/src/store/postPage.js
Labels: FE, feat

#33 [FE] 상품상세 페이지
  frontend/public/assets/product/chevron-left.svg
  frontend/public/assets/product/more.svg
  frontend/public/assets/product/small-chevron-down.svg
  frontend/src/App.js
  frontend/src/components/Carousel/index.js
  frontend/src/components/Carousel/style.scss
  frontend/src/components/Dropdown/style.scss
  frontend/src/components/ProductDetailBottomBar/index.js
  frontend/src/components/ProductDetailBottomBar/style.scss
  frontend/src/components/ProductDetailInfo/index.js
  frontend/src/components/ProductDetailInfo/style.scss
  frontend/src/components/ProductDetailTopBar/index.js
  frontend/src/components/ProductDetailTopBar/style.scss
  frontend/src/index.js
  frontend/src/pages/ProductDetailPage/index.js
  frontend/src/pages/ProductDetailPage/style.scss
  frontend/src/style/variables.scss
Labels: FE, feat

#35 [BE] 유저, 동네, 상품 API
  backend/app.js
  backend/db.js
  backend/ddl/ddl.sql
  backend/query/chat.js
  backend/query/product.js
  backend/routes/apiRouter.js
  backend/routes/chat.js
  backend/routes/product.js
  backend/routes/town.js
  backend/routes/user.js
  configs/config.dev.json
  frontend/src/components/Chatting/ChatProductInfo/index.js
  frontend/src/components/Common/CommonTopBar/index.js
  frontend/src/components/ProductDetailBottomBar/index.js
  frontend/src/components/ProductDetailInfo/index.js
  frontend/src/components/ProductDetailTopBar/index.js
  frontend/src/pages/CategoryPage/index.js
  frontend/src/pages/ChatPage/index.js
  frontend/src/pages/LocationEditPage/index.js
  frontend/src/pages/LoginPage/index.js
  frontend/src/pages/LogoutPage/index.js
  frontend/src/pages/MenuPage/index.js
  frontend/src/pages/PostPage/index.js
  frontend/src/pages/ProductDetailPage/index.js
  frontend/src/pages/RegisterPage/index.js
  package-lock.json
  package.json
Labels: BE, feat

#36 [BE] 관심 관련 API
  backend/query/like.js
  backend/query/product.js
  backend/routes/apiRouter.js
  backend/routes/like.js
  backend/routes/product.js
Labels: BE, feat

#37 [BE] API 완성
  backend/app.js
  backend/middleware/auth.js
  backend/query/chat.js
  backend/query/like.js
  backend/routes/apiRouter.js
  backend/routes/chat.js
  backend/routes/like.js
  package-lock.json
  package.json
Labels: BE, feat

#40 [FE]상품 등록 페이지API 적용
  frontend/public/assets/postPage/disableSubmitButton.svg
  frontend/public/assets/postPage/submitButton.svg
  frontend/src/API/api.js
  frontend/src/API/imgAPI.js
  frontend/src/API/productAPI.js
  frontend/src/components/PostProductForm/FormImgList/index.js
  frontend/src/components/PostProductForm/FormTitleNCategory/index.js
  frontend/src/components/PostProductForm/FormTitleNCategory/style.scss
  frontend/src/components/PostProductForm/index.js
  frontend/src/pages/PostPage/index.js
  frontend/src/store/postPage.js
  frontend/src/utils/globalObserver.js
  frontend/webpack.config.js
Labels: FE, feat

#43 [FE] 사용자 인증 관련 API 적용
  backend/routes/user.js
  frontend/src/API/userAPI.js
  frontend/src/components/LoginForm/index.js
  frontend/src/components/LogoutForm/index.js
  frontend/src/components/MainTopBar/index.js
  frontend/src/components/RegisterForm/index.js
  frontend/src/index.js
  frontend/src/lib/route.js
  frontend/src/store/user.js
  frontend/webpack.config.js
Labels: FE, feat

#46 [FE] 동네페이지 완료
  backend/routes/user.js
  frontend/src/API/api.js
  frontend/src/API/chatAPI.js
  frontend/src/API/imgAPI.js
  frontend/src/API/productAPI.js
  frontend/src/API/townAPI.js
  frontend/src/components/ChatList/ChatItem.js
  frontend/src/components/Chatting/Chatting.js
  frontend/src/components/Dropdown/LocationDropdown.js
  frontend/src/components/LocationList/LocationItem.js
  frontend/src/components/LocationList/index.js
  frontend/src/components/LocationList/style.scss
  frontend/src/components/LoginForm/index.js
  frontend/src/components/MainTopBar/index.js
  frontend/src/components/MainTopBar/style.scss
  frontend/src/components/Popup/LocationInputPopup.js
  frontend/src/components/PostProductForm/FormImgList/index.js
  frontend/src/components/ProductList/ProductItem.js
  frontend/src/components/ProductList/style.scss
  frontend/src/pages/ChatPage/index.js
  frontend/src/pages/HomePage/index.js
  frontend/src/pages/LocationEditPage/index.js
  frontend/src/pages/LocationEditPage/style.scss
  frontend/src/pages/MenuPage/index.js
  frontend/src/pages/PostPage/index.js
  frontend/src/store/chattingPage.js
  frontend/src/store/townPage.js
Labels: FE, feat, fix

#50 [Fix] API response 수정
  backend/routes/chat.js
  backend/routes/like.js
  backend/routes/product.js
  backend/routes/town.js
  frontend/src/API/productAPI.js
  frontend/src/components/Popup/LocationInputPopup.js
  frontend/src/pages/ChatPage/index.js
  frontend/src/pages/MenuPage/index.js
Labels: BE, FE, fix

#53 [Fix] townState를 userState로 통일
  frontend/src/components/Dropdown/LocationDropdown.js
  frontend/src/components/LocationList/LocationItem.js
  frontend/src/components/LocationList/index.js
  frontend/src/components/LoginForm/index.js
  frontend/src/components/MainTopBar/index.js
  frontend/src/components/Popup/LocationInputPopup.js
  frontend/src/pages/PostPage/index.js
  frontend/src/store/townPage.js
Labels: FE, fix

#54 [Fix] 빈 메세지 전송 불가 및 채팅방 스크롤
  frontend/src/components/Chatting/Chatting.js
  frontend/src/pages/ChatPage/index.js
Labels: FE, feat

#55 [FE] 채팅방 삭제 모달
  frontend/src/API/chatAPI.js
  frontend/src/components/ChatList/ChatItem.js
  frontend/src/components/Chatting/ChatDeleteBtn.js
  frontend/src/components/Chatting/Chatting.js
  frontend/src/components/Popup/ChattingDeletePopup.js
  frontend/src/components/Popup/LocationInputPopup.js
  frontend/src/components/Popup/style.scss
  frontend/src/index.js
  frontend/src/pages/ChatPage/index.js
  frontend/src/pages/ChatPage/style.scss
  frontend/src/pages/LocationEditPage/style.scss
  frontend/src/store/store.js
Labels: FE, feat

#57 [FE] 메인페이지 상품리스트 조회 및 상품리스트 아이템 상호작용
  backend/query/product.js
  backend/routes/chat.js
  backend/routes/product.js
  frontend/src/API/chatAPI.js
  frontend/src/API/productAPI.js
  frontend/src/components/ProductDetailBottomBar/index.js
  frontend/src/components/ProductDetailTopBar/index.js
  frontend/src/components/ProductList/ProductItem.js
  frontend/src/components/ProductList/index.js
  frontend/src/components/ProductList/style.scss
  frontend/src/pages/HomePage/index.js
Labels: FE, feat

#58 [FE] 채팅 리스트 api 연동 및 오류 수정
  backend/routes/product.js
  frontend/src/API/chatAPI.js
  frontend/src/components/ChatList/ChatItem.js
  frontend/src/index.js
  frontend/src/pages/ChatListPage/index.js
  frontend/src/pages/PostPage/index.js
Labels: BE, FE, feat, fix

#60 [FE] 상품 수정페이지
  frontend/src/API/productAPI.js
  frontend/src/components/PostProductForm/index.js
  frontend/src/index.js
  frontend/src/pages/PostPage/index.js
  frontend/src/pages/ProductEditPage/index.js
Labels: FE, feat

#63 [FE,BE][Fix] 채팅창 관련 오류 수정
  backend/query/chat.js
  backend/routes/chat.js
  frontend/src/components/Chatting/Chatting.js
Labels: BE, FE, fix

#61 [FE] 카테고리 토글 (#51)
  frontend/src/components/CategoryContainer/index.js
Labels: FE, feat

#62 [FE] getWon, getPassedTime 작성 (#32)
  frontend/src/utils/convertToString.js
Labels: FE, feat

#64 [FE] 캐러셀 컴포넌트 (#26)
  backend/routes/product.js
  frontend/src/components/Carousel/index.js
Labels: FE, feat

#67 [FE] 채팅 메세지 위치 수정, 채팅 방식 변경
  backend/query/chat.js
  frontend/src/components/Chatting/Chatting.js
  frontend/src/pages/ChatPage/index.js
Labels: FE, feat, fix

#66 [FE] dropbox wrapper 외부 클릭 시 닫기 (#65)
  frontend/src/components/MainTopBar/index.js
  frontend/src/components/ProductDetailInfo/index.js
  frontend/src/components/ProductDetailTopBar/index.js
  frontend/src/components/ProductList/ProductItem.js
Labels: FE, feat

#70 [FE] (css) 앱, 페이지 전환 및 Fab 버튼 위치
  frontend/src/App.js
  frontend/src/pages/HomePage/style.scss
  frontend/src/style/style.scss
Labels: FE, feat
